import { writeFileSync, readFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { OutputFile } from '../types/composer.types.js';

export interface WriteResult {
  written: string[];
  skipped: string[];
}

export function writeOutputFiles(
  files: OutputFile[],
  projectDir: string,
  force: boolean = false,
): WriteResult {
  const written: string[] = [];
  const skipped: string[] = [];

  for (const file of files) {
    const absolutePath = resolve(projectDir, file.path);
    const dir = dirname(absolutePath);

    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }

    if (existsSync(absolutePath) && !force) {
      const existing = readFileSync(absolutePath, 'utf-8');
      if (!existing.includes('Generated by Context Builder')) {
        skipped.push(file.path);
        continue;
      }
    }

    writeFileSync(absolutePath, file.content, 'utf-8');
    written.push(file.path);
  }

  return { written, skipped };
}
