import type { ResolvedRule } from '../types/rule.types.js';
import type { CompositionResult } from '../types/composer.types.js';
import type { StandardWorkflowConfig } from '../types/config.types.js';
import type { TargetDefinition } from '../targets/target.types.js';

function buildHeader(target: TargetDefinition, rules: ResolvedRule[]): string {
  const slugs = rules.map((r) => r.slug).join(', ');
  return [
    '<!-- Generated by Context Builder — do not edit manually -->',
    `<!-- Target: ${target.name} | Type: standard -->`,
    `<!-- Rules: ${slugs} -->`,
  ].join('\n');
}

function ensureHeading(rule: ResolvedRule): string {
  const content = rule.content;
  if (content.startsWith('# ')) {
    return content;
  }
  const title = rule.frontmatter?.name ?? slugToTitle(rule.slug);
  return `# ${title}\n\n${content}`;
}

function slugToTitle(slug: string): string {
  const name = slug.split('/').pop() ?? slug;
  return name
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

export function composeStandard(
  rules: ResolvedRule[],
  config: StandardWorkflowConfig,
  target: TargetDefinition,
  outputPath: string,
): CompositionResult {
  const header = buildHeader(target, rules);
  const preamble = config.preamble ? `\n${config.preamble}\n\n---` : '';

  const body = rules
    .map((rule, index) => {
      const separator = index > 0 ? '\n---\n\n' : '';
      return `${separator}${ensureHeading(rule)}`;
    })
    .join('\n');

  const mainContent = `${header}${preamble}\n\n${body}\n`;
  const finalContent = target.transformOutput
    ? target.transformOutput(mainContent, { type: 'main' })
    : mainContent;

  return {
    mainFile: {
      path: outputPath,
      content: finalContent,
    },
    stepFiles: [],
  };
}
