import type { ResolvedRule } from '../types/rule.types.js';
import type { CompositionResult } from '../types/composer.types.js';
import type { StandardWorkflowConfig } from '../types/config.types.js';
import type { TargetDefinition } from '../targets/target.types.js';

function buildHeader(
  target: TargetDefinition,
  beforeStart: ResolvedRule[],
  rules: ResolvedRule[],
  beforeFinish: ResolvedRule[],
): string {
  const slugs = [...beforeStart, ...rules, ...beforeFinish].map((r) => r.slug).join(', ');
  return [
    '<!-- Generated by AI Rulesmith — do not edit manually -->',
    `<!-- Target: ${target.name} | Type: standard -->`,
    `<!-- Rules: ${slugs} -->`,
  ].join('\n');
}

function ensureHeading(rule: ResolvedRule): string {
  const content = rule.content;
  if (content.startsWith('# ')) {
    return content;
  }
  const title = rule.frontmatter?.name ?? slugToTitle(rule.slug);
  return `# ${title}\n\n${content}`;
}

function slugToTitle(slug: string): string {
  const name = slug.split('/').pop() ?? slug;
  return name
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function renderRulesBlock(rules: ResolvedRule[]): string {
  return rules
    .map((rule, index) => {
      const separator = index > 0 ? '\n---\n\n' : '';
      return `${separator}${ensureHeading(rule)}`;
    })
    .join('\n');
}

export function composeStandard(
  rules: ResolvedRule[],
  beforeStart: ResolvedRule[],
  beforeFinish: ResolvedRule[],
  config: StandardWorkflowConfig,
  target: TargetDefinition,
  outputPath: string,
): CompositionResult {
  const header = buildHeader(target, beforeStart, rules, beforeFinish);
  const preamble = config.preamble ? `\n${config.preamble}\n\n---` : '';

  const parts: string[] = [header, preamble];

  if (beforeStart.length > 0) {
    parts.push(
      '',
      '# Before You Start',
      '',
      'IMPORTANT: Complete these steps before writing any code.',
      '',
      renderRulesBlock(beforeStart),
      '',
      '---',
    );
  }

  parts.push('', renderRulesBlock(rules));

  if (beforeFinish.length > 0) {
    parts.push(
      '',
      '---',
      '',
      '# Before You Finish',
      '',
      'IMPORTANT: Do NOT skip these steps after completing your work.',
      '',
      renderRulesBlock(beforeFinish),
    );
  }

  parts.push('');

  const mainContent = parts.join('\n');
  const finalContent = target.transformOutput
    ? target.transformOutput(mainContent, { type: 'main' })
    : mainContent;

  return {
    mainFile: {
      path: outputPath,
      content: finalContent,
    },
    stepFiles: [],
  };
}
