import type { ResolvedRule } from '../types/rule.types.js';
import type { CompositionResult, OutputFile } from '../types/composer.types.js';
import type { StepsWorkflowConfig, StepConfig } from '../types/config.types.js';
import type { TargetDefinition } from '../targets/target.types.js';

function stepSlug(stepName: string): string {
  return stepName
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '');
}

function resolveStepFilePath(pattern: string, index: number, name: string): string {
  return pattern
    .replace('{{step_index}}', String(index))
    .replace('{{step_slug}}', stepSlug(name));
}

function slugToTitle(slug: string): string {
  const name = slug.split('/').pop() ?? slug;
  return name
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function ensureHeading(rule: ResolvedRule): string {
  const content = rule.content;
  if (content.startsWith('# ') || content.startsWith('## ')) {
    return content;
  }
  const title = rule.frontmatter?.name ?? slugToTitle(rule.slug);
  return `## ${title}\n\n${content}`;
}

function renderRulesBlock(rules: ResolvedRule[]): string {
  return rules
    .map((rule, index) => {
      const separator = index > 0 ? '\n---\n\n' : '';
      return `${separator}${ensureHeading(rule)}`;
    })
    .join('\n');
}

function allSlugs(
  beforeStart: ResolvedRule[],
  rules: ResolvedRule[],
  beforeFinish: ResolvedRule[],
): string {
  return [...beforeStart, ...rules, ...beforeFinish].map((r) => r.slug).join(', ');
}

interface StepRules {
  step: StepConfig;
  rules: ResolvedRule[];
  beforeStart: ResolvedRule[];
  beforeFinish: ResolvedRule[];
}

function composeStepFile(
  stepIndex: number,
  { step, rules, beforeStart, beforeFinish }: StepRules,
  target: TargetDefinition,
  stepFilePath: string,
): OutputFile {
  const header = [
    '<!-- Generated by AI Rulesmith — do not edit manually -->',
    `<!-- Step ${stepIndex}: ${step.step_name} -->`,
    `<!-- Rules: ${allSlugs(beforeStart, rules, beforeFinish)} -->`,
  ].join('\n');

  const parts: string[] = [
    header,
    '',
    `# Step ${stepIndex}: ${step.step_name}`,
    '',
    'IMPORTANT: Follow ALL rules below during this step.',
  ];

  if (beforeStart.length > 0) {
    parts.push(
      '',
      '# Before You Start',
      '',
      'IMPORTANT: Complete these steps before writing any code.',
      '',
      renderRulesBlock(beforeStart),
    );
  }

  if (rules.length > 0) {
    parts.push('', '---', '', renderRulesBlock(rules));
  }

  if (beforeFinish.length > 0) {
    parts.push(
      '',
      '---',
      '',
      '# Before You Finish',
      '',
      'IMPORTANT: Do NOT skip these steps after completing your work.',
      '',
      renderRulesBlock(beforeFinish),
    );
  }

  parts.push('');

  const content = parts.join('\n');
  const finalContent = target.transformOutput
    ? target.transformOutput(content, {
        type: 'step',
        stepIndex,
        stepName: step.step_name,
        stepSlug: stepSlug(step.step_name),
      })
    : content;

  return {
    path: stepFilePath,
    content: finalContent,
  };
}

export function composeSteps(
  stepsWithRules: StepRules[],
  config: StepsWorkflowConfig,
  target: TargetDefinition,
  outputPath: string,
): CompositionResult {
  const header = [
    '<!-- Generated by AI Rulesmith — do not edit manually -->',
    `<!-- Target: ${target.name} | Type: steps -->`,
  ].join('\n');

  const preamble = config.preamble ? `\n${config.preamble}\n\n---` : '';

  const stepFilePattern = target.output.stepFilePattern;
  const stepFiles: OutputFile[] = [];
  const totalSteps = stepsWithRules.length;

  const hasPriorityZones = stepsWithRules.some(
    (s) => s.beforeStart.length > 0 || s.beforeFinish.length > 0,
  );

  const stepsMarkdown = stepsWithRules
    .map((stepData, index) => {
      const { step, rules, beforeStart, beforeFinish } = stepData;
      const stepIndex = index + 1;
      const stepDescription = step.description ? `\n${step.description}\n` : '';

      if (stepFilePattern && target.output.supportsFileReferences) {
        const stepFilePath = resolveStepFilePath(stepFilePattern, stepIndex, step.step_name);
        stepFiles.push(composeStepFile(stepIndex, stepData, target, stepFilePath));

        const stepGate = stepIndex < totalSteps
          ? `\nDo NOT proceed to Step ${stepIndex + 1} until Step ${stepIndex} work is complete.`
          : '';

        return [
          `## Step ${stepIndex}: ${step.step_name}`,
          stepDescription,
          `Read \`${stepFilePath}\` and follow all rules in that file.`,
          stepGate,
        ]
          .filter(Boolean)
          .join('\n');
      } else {
        // Inline mode: embed rules directly in the main file
        const inlineParts: string[] = [];

        if (beforeStart.length > 0) {
          inlineParts.push(
            '### Before You Start\n',
            'IMPORTANT: Complete these steps before writing any code.\n',
            renderRulesBlock(beforeStart),
            '\n---\n',
          );
        }

        inlineParts.push(renderRulesBlock(rules));

        if (beforeFinish.length > 0) {
          inlineParts.push(
            '\n---\n',
            '### Before You Finish\n',
            'IMPORTANT: Do NOT skip these steps after completing your work.\n',
            renderRulesBlock(beforeFinish),
          );
        }

        return [
          `## Step ${stepIndex}: ${step.step_name}`,
          stepDescription,
          inlineParts.join('\n'),
        ]
          .filter(Boolean)
          .join('\n\n');
      }
    })
    .join('\n\n');

  const workflowIntroParts = [
    'IMPORTANT: This project uses a mandatory step-based workflow.',
    'You MUST follow these steps in order. Do NOT skip ahead.',
  ];

  if (target.output.supportsFileReferences) {
    if (hasPriorityZones) {
      workflowIntroParts.push(
        '',
        'For each step:',
        '1. Read the rules file listed below',
        '2. Follow the "Before You Start" section first',
        '3. Do your implementation work following all rules',
        '4. Complete the "Before You Finish" section before moving on',
      );
    } else {
      workflowIntroParts.push(
        '',
        'Before starting any work, read the rules file for the current step.',
      );
    }
  }

  const workflowIntro = workflowIntroParts.join('\n');

  const mainContent = [
    header,
    preamble,
    '',
    '# Workflow',
    '',
    workflowIntro,
    '',
    stepsMarkdown,
    '',
  ]
    .filter((line) => line !== undefined)
    .join('\n');

  const finalMainContent = target.transformOutput
    ? target.transformOutput(mainContent, { type: 'main' })
    : mainContent;

  return {
    mainFile: {
      path: outputPath,
      content: finalMainContent,
    },
    stepFiles,
  };
}
