import type { ResolvedRule } from '../types/rule.types.js';
import type { CompositionResult, OutputFile } from '../types/composer.types.js';
import type { StepsWorkflowConfig, StepConfig } from '../types/config.types.js';
import type { TargetDefinition } from '../targets/target.types.js';

function stepSlug(stepName: string): string {
  return stepName
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '');
}

function resolveStepFilePath(pattern: string, index: number, name: string): string {
  return pattern
    .replace('{{step_index}}', String(index))
    .replace('{{step_slug}}', stepSlug(name));
}

function slugToTitle(slug: string): string {
  const name = slug.split('/').pop() ?? slug;
  return name
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function ensureHeading(rule: ResolvedRule): string {
  const content = rule.content;
  if (content.startsWith('# ') || content.startsWith('## ')) {
    return content;
  }
  const title = rule.frontmatter?.name ?? slugToTitle(rule.slug);
  return `## ${title}\n\n${content}`;
}

function composeStepFile(
  stepIndex: number,
  step: StepConfig,
  rules: ResolvedRule[],
  target: TargetDefinition,
  stepFilePath: string,
): OutputFile {
  const header = [
    '<!-- Generated by Context Builder — do not edit manually -->',
    `<!-- Step ${stepIndex}: ${step.step_name} -->`,
    `<!-- Rules: ${rules.map((r) => r.slug).join(', ')} -->`,
  ].join('\n');

  const body = rules
    .map((rule, index) => {
      const separator = index > 0 ? '\n---\n\n' : '';
      return `${separator}${ensureHeading(rule)}`;
    })
    .join('\n');

  const content = `${header}\n\n# Step ${stepIndex}: ${step.step_name}\n\n${body}\n`;
  const finalContent = target.transformOutput
    ? target.transformOutput(content, {
        type: 'step',
        stepIndex,
        stepName: step.step_name,
        stepSlug: stepSlug(step.step_name),
      })
    : content;

  return {
    path: stepFilePath,
    content: finalContent,
  };
}

export function composeSteps(
  stepsWithRules: Array<{ step: StepConfig; rules: ResolvedRule[] }>,
  config: StepsWorkflowConfig,
  target: TargetDefinition,
  outputPath: string,
): CompositionResult {
  const header = [
    '<!-- Generated by Context Builder — do not edit manually -->',
    `<!-- Target: ${target.name} | Type: steps -->`,
  ].join('\n');

  const preamble = config.preamble ? `\n${config.preamble}\n` : '';

  const stepFilePattern = target.output.stepFilePattern;
  const stepFiles: OutputFile[] = [];

  const stepsMarkdown = stepsWithRules
    .map(({ step, rules }, index) => {
      const stepIndex = index + 1;
      const stepDescription = step.description ? `\n${step.description}\n` : '';

      if (stepFilePattern && target.output.supportsFileReferences) {
        const stepFilePath = resolveStepFilePath(stepFilePattern, stepIndex, step.step_name);
        stepFiles.push(composeStepFile(stepIndex, step, rules, target, stepFilePath));

        return [
          `## Step ${stepIndex}: ${step.step_name}`,
          stepDescription,
          `**Rules file:** Read \`${stepFilePath}\` before starting this step.`,
        ]
          .filter(Boolean)
          .join('\n');
      } else {
        // Inline mode: embed rules directly in the main file
        const rulesContent = rules
          .map((rule) => ensureHeading(rule))
          .join('\n\n---\n\n');

        return [
          `## Step ${stepIndex}: ${step.step_name}`,
          stepDescription,
          rulesContent,
        ]
          .filter(Boolean)
          .join('\n\n');
      }
    })
    .join('\n\n');

  const mainContent = [
    header,
    preamble,
    '',
    '# Workflow Instructions',
    '',
    'This project uses a step-based workflow. Follow the steps below in order.',
    target.output.supportsFileReferences
      ? '**For each step, read the referenced rule file before starting work on that step.**'
      : '',
    '',
    stepsMarkdown,
    '',
  ]
    .filter((line) => line !== undefined)
    .join('\n');

  const finalMainContent = target.transformOutput
    ? target.transformOutput(mainContent, { type: 'main' })
    : mainContent;

  return {
    mainFile: {
      path: outputPath,
      content: finalMainContent,
    },
    stepFiles,
  };
}
