import { Command } from 'commander';
import { resolve } from 'node:path';
import { loadConfig } from '../../core/config-loader.js';
import { buildAll } from '../../core/composer.js';
import { writeOutputFiles } from '../../core/file-writer.js';
import { renderPreview, renderFileSummary } from '../ui/preview-renderer.js';
import { confirm } from '../ui/prompts.js';
import { log } from '../ui/logger.js';

export const buildCommand = new Command('build')
  .description('Compose rules into AI agent context files')
  .option('-c, --config <path>', 'Path to AI_RULES.json', './AI_RULES.json')
  .option('-t, --target <name>', 'Build only for a specific target')
  .option('--no-preview', 'Skip the preview step')
  .option('--dry-run', 'Show preview only, do not write files')
  .option('--force', 'Overwrite existing files without confirmation')
  .action(async (options) => {
    const projectDir = process.cwd();
    const configPath = resolve(projectDir, options.config);

    let configs;
    try {
      configs = loadConfig(configPath);
    } catch (err) {
      log.error((err as Error).message);
      process.exit(1);
    }

    const result = buildAll(configs, projectDir, options.target);

    if (result.errors.length > 0) {
      for (const err of result.errors) {
        log.error(`[${err.targetName}] ${err.message}`);
      }
      if (result.outputs.length === 0) {
        process.exit(1);
      }
    }

    if (result.outputs.length === 0) {
      log.warn('No outputs to build.');
      return;
    }

    // Preview
    if (options.preview !== false) {
      for (const output of result.outputs) {
        renderPreview(output.targetName, output.composition);
      }
    }

    // Summary
    log.blank();
    log.heading('Build Summary');
    for (const output of result.outputs) {
      log.blank();
      log.info(`Target: ${output.targetName}`);
      renderFileSummary(output.composition);
    }

    if (options.dryRun) {
      log.blank();
      log.dim('Dry run — no files written.');
      return;
    }

    // Confirm
    if (!options.force) {
      log.blank();
      const totalFiles = result.outputs.reduce(
        (sum, o) => sum + 1 + o.composition.stepFiles.length,
        0,
      );
      const yes = await confirm(`Write ${totalFiles} file(s) to disk?`);
      if (!yes) {
        log.dim('Aborted.');
        return;
      }
    }

    // Write
    for (const output of result.outputs) {
      const allFiles = [output.composition.mainFile, ...output.composition.stepFiles];
      const writeResult = writeOutputFiles(allFiles, projectDir, options.force);

      for (const path of writeResult.written) {
        log.file(path);
      }
      for (const path of writeResult.skipped) {
        log.warn(`Skipped (not generated by Context Builder): ${path}`);
      }
    }

    log.blank();
    log.success('Done!');
  });
